Description: 'Challange 3 AB/ Udacity'

Parameters:
  AmiToUse:
    Description: An env name with prefix
    Type: String
  

Resources:

  RoleForSSMAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        !Ref RoleForSSMAccess

  WebAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Group for EC2 Cal3
      GroupName: EC2 group Challange 3
      VpcId:
          Fn::ImportValue:
            !Sub ${EnvironmentName}-VPCID
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  ServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: 
        !Ref AmiToUse
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            !Ref WebAccessSecuritygroup
          SubnetId: 
            Fn::ImportValue:
              !Sub ${EnvironmentName}-PRI1-SN
      